import { FILTERS } from "./FilterConstants";

export const placeholderCardData = [
  // Apple
  {
    name: "MacBook Air",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.COMPUTER,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "1199",
    isOnSale: false,
  },
  {
    name: "iPhone 14",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.PHONE,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "999",
    isOnSale: true,
  },
  {
    name: "iPad Mini",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.TABLET,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "549",
    isOnSale: false,
  },
  {
    name: "AirPods Pro",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.CANADA,
    imageUrl: "1",
    currentPrice: "249",
    isOnSale: true,
  },
  {
    name: "iPhone SE",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.PHONE,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.OTHER,
    imageUrl: "1",
    currentPrice: "429",
    isOnSale: false,
  },

  // Samsung
  {
    name: "Galaxy S23",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.PHONE,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.VIETNAM,
    imageUrl: "1",
    currentPrice: "899",
    isOnSale: false,
  },
  {
    name: "Galaxy Tab S8",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.TABLET,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.VIETNAM,
    imageUrl: "1",
    currentPrice: "749",
    isOnSale: true,
  },
  {
    name: "Galaxy Buds 2",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.US,
    imageUrl: "1",
    currentPrice: "149",
    isOnSale: false,
  },
  {
    name: "Samsung Chromebook",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.COMPUTER,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.OTHER,
    imageUrl: "1",
    currentPrice: "499",
    isOnSale: true,
  },
  {
    name: "Galaxy A14",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.PHONE,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.OTHER,
    imageUrl: "1",
    currentPrice: "199",
    isOnSale: false,
  },

  // Google
  {
    name: "Pixel 8",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.PHONE,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.VIETNAM,
    imageUrl: "1",
    currentPrice: "699",
    isOnSale: false,
  },
  {
    name: "Pixel Buds Pro",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.US,
    imageUrl: "1",
    currentPrice: "199",
    isOnSale: false,
  },
  {
    name: "Pixelbook Go",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.COMPUTER,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CANADA,
    imageUrl: "1",
    currentPrice: "849",
    isOnSale: true,
  },
  {
    name: "Pixel Tablet",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.TABLET,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "599",
    isOnSale: false,
  },
  {
    name: "Pixel 6a",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.PHONE,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.VIETNAM,
    imageUrl: "1",
    currentPrice: "349",
    isOnSale: true,
  },

  // Other
  {
    name: "Lenovo Yoga",
    brand: FILTERS.brands.OTHER,
    type: FILTERS.types.COMPUTER,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "899",
    isOnSale: false,
  },
  {
    name: "Motorola G Power",
    brand: FILTERS.brands.OTHER,
    type: FILTERS.types.PHONE,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.CANADA,
    imageUrl: "1",
    currentPrice: "249",
    isOnSale: false,
  },
  {
    name: "Fire HD 10",
    brand: FILTERS.brands.OTHER,
    type: FILTERS.types.TABLET,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.OTHER,
    imageUrl: "1",
    currentPrice: "149",
    isOnSale: true,
  },
  {
    name: "Logitech MX Mouse",
    brand: FILTERS.brands.OTHER,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "99",
    isOnSale: false,
  },
  {
    name: "Dell XPS 13",
    brand: FILTERS.brands.OTHER,
    type: FILTERS.types.COMPUTER,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.US,
    imageUrl: "1",
    currentPrice: "1099",
    isOnSale: true,
  },

  // Repeat mix to reach 30 items (copies with minor changes)
  {
    name: "iPad 9th Gen",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.TABLET,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.CANADA,
    imageUrl: "1",
    currentPrice: "429",
    isOnSale: false,
  },
  {
    name: "Galaxy Tab A8",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.TABLET,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.OTHER,
    imageUrl: "1",
    currentPrice: "279",
    isOnSale: true,
  },
  {
    name: "Google Nest Hub",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "129",
    isOnSale: false,
  },
  {
    name: "Apple Magic Keyboard",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "549",
    isOnSale: false,
  },
  {
    name: "Samsung Smart Monitor",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.US,
    imageUrl: "1",
    currentPrice: "599",
    isOnSale: true,
  },
  {
    name: "Google Pixel Slate",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.TABLET,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CANADA,
    imageUrl: "1",
    currentPrice: "799",
    isOnSale: false,
  },
  {
    name: "Samsung Galaxy Watch 6",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.US,
    imageUrl: "1",
    currentPrice: "399",
    isOnSale: true,
  },
  {
    name: 'Apple iMac 24"',
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.COMPUTER,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "1299",
    isOnSale: false,
  },
  {
    name: "Lenovo Tab M10",
    brand: FILTERS.brands.OTHER,
    type: FILTERS.types.TABLET,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.OTHER,
    imageUrl: "1",
    currentPrice: "189",
    isOnSale: true,
  },
  {
    name: "Google Pixel Fold",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.PHONE,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "1799",
    isOnSale: false,
  },
  {
    name: "Samsung Galaxy Book3",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.COMPUTER,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.US,
    imageUrl: "1",
    currentPrice: "1399",
    isOnSale: true,
  },
  {
    name: "Apple Pencil (2nd Gen)",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "129",
    isOnSale: false,
  },
  {
    name: "Google Pixel Buds A-Series",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.US,
    imageUrl: "1",
    currentPrice: "99",
    isOnSale: true,
  },
  {
    name: "Amazon Fire Max 11",
    brand: FILTERS.brands.OTHER,
    type: FILTERS.types.TABLET,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.OTHER,
    imageUrl: "1",
    currentPrice: "529",
    isOnSale: false,
  },
  {
    name: "Samsung Galaxy A54",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.PHONE,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.VIETNAM,
    imageUrl: "1",
    currentPrice: "449",
    isOnSale: true,
  },
];
