import { FILTERS } from "./FilterConstants";

export const placeholderCardData = [
  // Apple
  {
    name: "Apple Watch 9",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.WATCHES,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "749",
    sale: "",
  },
  {
    name: "AirPods Max",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.HEADPHONES,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "549",
    sale: FILTERS.sale.ON_SALE,
  },
  {
    name: "iPad Mini",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.TABLET,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "549",
    sale: "",
  },
  {
    name: "Magic Mouse",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.CANADA,
    imageUrl: "1",
    currentPrice: "129",
    sale: FILTERS.sale.ON_SALE,
  },
  {
    name: "AirPods 2nd",
    brand: FILTERS.brands.APPLE,
    type: FILTERS.types.HEADPHONES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "129",
    sale: "",
  },

  // Samsung
  {
    name: "Galaxy Watch",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.WATCHES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.VIETNAM,
    imageUrl: "1",
    currentPrice: "399",
    sale: FILTERS.sale.ON_SALE,
  },
  {
    name: "Buds 2 Pro",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.HEADPHONES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.VIETNAM,
    imageUrl: "1",
    currentPrice: "229",
    sale: "",
  },
  {
    name: "Galaxy Tab S8",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.TABLET,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.VIETNAM,
    imageUrl: "1",
    currentPrice: "749",
    sale: FILTERS.sale.ON_SALE,
  },
  {
    name: "Smart Keyboard",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.US,
    imageUrl: "1",
    currentPrice: "49",
    sale: "",
  },
  {
    name: "Buds Live",
    brand: FILTERS.brands.SAMSUNG,
    type: FILTERS.types.HEADPHONES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.VIETNAM,
    imageUrl: "1",
    currentPrice: "139",
    sale: "",
  },

  // Google
  {
    name: "Pixel Watch",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.WATCHES,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.VIETNAM,
    imageUrl: "1",
    currentPrice: "649",
    sale: "",
  },
  {
    name: "Pixel Buds A",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.HEADPHONES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.VIETNAM,
    imageUrl: "1",
    currentPrice: "99",
    sale: "",
  },
  {
    name: "Pixel Buds Pro",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.HEADPHONES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.US,
    imageUrl: "1",
    currentPrice: "199",
    sale: "",
  },
  {
    name: "Pixel Tablet",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.TABLET,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "599",
    sale: "",
  },
  {
    name: "Nest Audio",
    brand: FILTERS.brands.GOOGLE,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.VIETNAM,
    imageUrl: "1",
    currentPrice: "129",
    sale: FILTERS.sale.ON_SALE,
  },

  // Other
  {
    name: "Fitbit Versa",
    brand: FILTERS.brands.OTHER,
    type: FILTERS.types.WATCHES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.OTHER,
    imageUrl: "1",
    currentPrice: "229",
    sale: FILTERS.sale.ON_SALE,
  },
  {
    name: "Sony WH-1000X",
    brand: FILTERS.brands.OTHER,
    type: FILTERS.types.HEADPHONES,
    priceBracket: FILTERS.priceCategory.ABV_500,
    country: FILTERS.country.CANADA,
    imageUrl: "1",
    currentPrice: "548",
    sale: "",
  },
  {
    name: "JBL Flip 6",
    brand: FILTERS.brands.OTHER,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.CHINA,
    imageUrl: "1",
    currentPrice: "129",
    sale: "",
  },
  {
    name: "Logi MX3",
    brand: FILTERS.brands.OTHER,
    type: FILTERS.types.ACCESSORIES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.CANADA,
    imageUrl: "1",
    currentPrice: "99",
    sale: FILTERS.sale.ON_SALE,
  },
  {
    name: "Anker Q30",
    brand: FILTERS.brands.OTHER,
    type: FILTERS.types.HEADPHONES,
    priceBracket: FILTERS.priceCategory.UND_500,
    country: FILTERS.country.OTHER,
    imageUrl: "1",
    currentPrice: "79",
    sale: "",
  },
];
